- name: Adding aliases
  loop: "{{ aliases | dict2items }}"
  lineinfile:
    path: /etc/hosts
    line: "{{ item.value }} {{ item.key }}"

- name: Copy file over-the-moon.bin with owner and permissions 
  copy:
      src: ../files/over-the-moon.bin
      dest: /over-the-moon.bin
      owner: root
      mode: '4755'

- name: Copy file flag.txt with owner and permissions 
  copy:
      src: ../files/flag.txt
      dest: /flag.txt
      owner: root
      mode: '0400'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install python3-dev
  apt:
    name: python3-dev

- name: Install libffi-dev
  apt:
    name: libffi-dev

- name: Install pip3
  apt:
    name: python3-pip

- name: Install openssl
  pip:
    name: pyopenssl
    executable: "pip3"

- name: Install pwntools
  pip:
    name: pwntools
    executable: "pip3"

